### ISSUE TITLE
Bug when moving list items up and down

### ISSUE THREAD

**Issue by andmis** [lervag/lists.vim#3]
On latest `main`, using the following file:

```
- A
  - B
- C
  - D
    - E
```

With the cursor on the `E`, doing `(lists-moveup)` followed by `(lists-movedown)` puts the `E` in a different place from where it started (I guess these ops should be inverses), and another `(lists-movedown)` causes an error to fire in the plugin.

**Comment by lervag** [comment]
You raise a valid issue. I spent some time thinking about these things. What do we want to happen if we move `E` up through the list? I think there are several choices here, because we need to choose how to treat the list level. In the current implementation, the idea is that moving list items do not change the level. Thus, moving `E` up should move it to `A -> B -> E`. This seems to work. Moving it down should move it back to the original spot, and I agree this seems to not work as expected.

The error occurs for the same reason, because the `E` entry now hangs without a close parent (it has level 3, whereas the parent has level 1). The code does not handle this error properly - I'll fix that as well.

**Comment by andmis** [comment]
I agree that moving vertically should not change the level, and off the top of my head I would say this should work the same way the plugin currently works for this snippet, which for some reason is different from the one I posted originally (which may itself be a different bug, the fact that the behavior differs):

```
- A
  * B
- C
  * D
    + E
```
(It moves both `D` and `E` up/down.)

**Comment by lervag** [comment]
I believe the original issue (both parts) is fixed now, please test.

**Comment by lervag** [comment]
The new snippet uses a new marker `+` which is not recognized as a list bullet. Thus, the text is considered a continuation of the item.

The core idea is more or less to use the indentation to determine the list items and list structure.

**Comment by andmis** [comment]
Just tested, LGTM. It looks like when moving a node, you jump to the nearest available slot at the node's level in the given direction, which I think makes sense and has the benefit of being easy to understand. Thanks again for the plugin!

**Comment by lervag** [comment]
Great; thanks for using this and reporting the issues! Glad to hear it works as expected for you.

I've updated the docs to clarify the types of lists supported. I hope that may make it clearer to other new users.
