### ISSUE TITLE
feature request: simpler status toggle using space (or other single mapping)

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/lists.vim#7]
I wonder if you would consider incorporating the "Switch Status" approach used by [gabrielelana/vim-markdown][1], where you just press `<space>` when on a list item to cycle through `- text` > `- [ ] text` > `- [x] text`. I find that simpler than the way `lists.vim` currently implements it. (But I much prefer the modular approach you've taken here, having one plugin for dealing with lists, another for syntax highlighting, etc. That also has the advantage of making it easier to apply this feature to any filetype, not just markdown.)

[1]: https://github.com/gabrielelana/vim-markdown/blob/772de97c97d37e5e22d7bd6884b17b858a687bc2/autoload/markdown.vim#L504

**Comment by lervag** [comment]
> I wonder if you would consider incorporating the "Switch Status" approach …, where you just press `<space>` when on a list item to cycle through `- text` > `- [ ] text` > `- [x] text`.

Are you aware of the current toggle mapping; by default `<c-s>`? It does this, partially. It does this:

```
- [ ] text                      - [x] text
- [x] text           <c-s>      - [ ] text
- text              ------>     - TODO: text
- TODO: text                    - text
```

It is documented under `:help ListsToggle` and the default mapping is listed under `:help lists-maps-defaults`.

> But I much prefer the modular approach you've taken here, having one plugin for dealing with lists, another for syntax highlighting, etc. That also has the advantage of making it easier to apply this feature to any filetype, not just markdown.

Yes, that is also the motivation had for going in this direction. I find it useful to have list features in many different filetypes. :)

**Comment by alexandreroberts** [comment]
Yes, I have been using the default `<c-s>` toggle mapping, but I miss two aspects of the gabrielelana/vim-markdown toggle:

1. the use of `<space>` for the mapping for ease of typing in normal mode (and I don't need it in other modes); I suspect this would be very easy for me to customize, ~~though I think gabrielelana/vim-markdown may do something slightly more sophisticated to make sure that `<space>` still has its native normal-mode meaning when the cursor is not on a list item~~ (I just checked and in fact I was wrong, it does not retain its native meaning; and I also just noticed that it can also be used to change headers `# header` > `## header`);
2. the fact that I can use it to add a checkbox to an ordinary list item (i.e., the `- text` > `- [ ] text` toggle that is missing in `list.vim`.

This second (and more important) difference might come into conflict with your current toggle mapping, since `<c-s>` currently does `- text` > `- TODO: text`. Perhaps they could coexist if `<c-s>` keeps doing what it currently does (thus I am not asking *you*, the plugin's author, to change your habits!) and then the `<space>` functionality is imported more or less in its entirety from gabrielelana/vim-markdown? Alternatively, there could be global option variables that would let one select which of the behaviors one preferred.

What do you think?

**Comment by lervag** [comment]
> I miss two aspects of the gabrielelana/vim-markdown toggle:
> 
> 1. the use of `<space>` for the mapping for ease of typing in normal mode (and I don't need it in other modes)

You can choose whichever mapping you want. `<space>` is very commonly used as the `<leader>` key, which makes it a very bad default mapping. But if you want to use `<space>` instead of `<c-s>` (and disable it in insert mode), then you can do this:

```vim
let g:lists_maps_default_override = {
      \ 'i_<plug>(lists-toggle)': '',
      \ '<plug>(lists-toggle)': '<space>',
      \}
```

> I also just noticed that it can also be used to change headers `# header` > `## header`

That's an entirely different feature. IMHO, it is out of scope as it does not concern lists and is very specific to markdown. I also think it is less important (adding `#` is simply `I#`, removing is `0x`).

> 2. the fact that I can use it to add a checkbox to an ordinary list item (i.e., the `- text` > `- [ ] text` toggle that is missing in `list.vim`.

Yes, true, this is not possible now. My reasoning is quite simple: A checkbox
list is _different_ semantically. If you want to make a list of checkboxes,
then this should be easy with lists.vim:

1. Create the first list entry with an empty checkbox.
2. Use the `<c-a>` mapping (see `:help lists-new-element`) to start new list entries, as it will add the desired initial indent and `- [ ]` automatically.

However, I could be convinced to either implement or change things here if you find this feature to be very important. If so, then I think we should probably have a dedicated checkbox toggle mapping that works like what you specify. I.e., we retain the current version of `lists-toggle`, but add `lists-toggle-checkbox` that behaves like this:

```
- text                          - [ ] text
- [ ] text           <c-s>      - [x] text
- [x] text          ------>     - [ ] text
```

> Alternatively, there could be global option variables that would let one select which of the behaviors one preferred.

I think a new mapping is better, as it allows to customize the behaviour at a slightly more detailed manner.

**Comment by lervag** [comment]
I've added this now. I think you will get the behaviour you want if you update and use the following configuration:

```vim
let g:lists_maps_default_override = {
      \ 'i_<plug>(lists-toggle)': '',
      \ '<plug>(lists-toggle)': '',
      \ '<plug>(lists-toggle-checkbox)': '<space>',
      \}
```

**Comment by alexandreroberts** [comment]
Wonderful, that new configuration works perfectly! Thanks so much for implementing this.

**Comment by alexandreroberts** [comment]
(And I agree that changing markdown headers is out of the scope of this plugin. As you say, one probably needs no mapping for it at all.)

**Comment by lervag** [comment]
> Wonderful, that new configuration works perfectly! Thanks so much for implementing this.

Glad to hear it! :)
